**Exercice 1**

In [ ]:
import numpy as np
import pandas as pd

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

# Solution
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
print(ser3.head())

a    0
b    1
c    2
e    3
d    4
dtype: int64

**Exercice 2**

In [ ]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

# Solution
df = ser.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4

**Exercice 3**

In [ ]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

# Solution 1
df = pd.concat([ser1, ser2], axis=1)

# Solution 2
df = pd.DataFrame({'col1': ser1, 'col2': ser2})
print(df.head())

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

**Exercice 4**

In [ ]:
# Input
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

# Solution
ser.name = 'alphabets'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

**Exercice 5**

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# Solution
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

**Exercice 6**

In [ ]:
# Input
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# Solution
ser_u = pd.Series(np.union1d(ser1, ser2))  # union
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

**Exercice 7**

In [ ]:
# Input
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10, 5, 25))

# Solution
np.percentile(ser, q=[0, 25, 50, 75, 100])

array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

**Exercice 8**

In [ ]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

# Solution
ser.value_counts()

b    7
a    7
c    5
g    3
d    2
h    2
f    2
e    2
dtype: int64

**Exercice 9**

In [ ]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

# Solution
print("Top 2 Freq:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

Top 2 Freq: 4    7
3    3
2    2
dtype: int64

0     Other
1         3
2         4
3         4
4         4
5         4
6         3
7         4
8         3
9         4
10    Other
11        4
dtype: object

**Exercice 10**

In [ ]:
ser = pd.Series(np.random.random(20))
print(ser.head())

# Solution
pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()

0    0.413641
1    0.436176
2    0.735381
3    0.365693
4    0.255007
dtype: float64

0    5th
1    5th
2    9th
3    4th
4    2nd
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

**Exercice 11**

In [ ]:
# Input
ser = pd.Series(np.random.randint(1, 10, 35))

# Solution
df = pd.DataFrame(ser.values.reshape(7,5))
print(df)

   0  1  2  3  4
0  9  8  4  4  8
1  9  4  2  8  6
2  7  9  4  6  2
3  4  6  8  5  1
4  2  1  5  8  6
5  5  4  6  2  2
6  2  5  7  4  4

**Exercice 12**

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 7))
ser

# Solution
print(ser)
np.where(ser % 3==0)

0    8
1    6
2    3
3    2
4    8
5    8
6    9
dtype: int64

(array([1, 2, 6]),)

**Exercice 13**

In [ ]:
# Input
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

# Solution
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

**Exercice 14**

In [ ]:
# Input
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

# Output
# Vertical
ser1.append(ser2)

# Horizontal
df = pd.concat([ser1, ser2], axis=1)
print(df)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

**Exercice 15**

In [ ]:
# Input
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

# Solution 1
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

# Solution 2
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

**Exercice 16**

In [ ]:
# Input
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

# Solution
np.mean((truth-pred)**2)

0.22491321855327376

**Exercice 17**

In [ ]:
ser = pd.Series(['how', 'to', 'say', 'hello?'])

# Solution 1
ser.map(lambda x: x.title())

# Solution 2
ser.map(lambda x: x[0].upper() + x[1:])

# Solution 3
pd.Series([i.title() for i in ser])

0       How
1        To
2       Say
3    Hello?
dtype: object

**Exercice 18**

In [ ]:
# Input
ser = pd.Series(['how', 'to', 'say', 'hello?'])

# Solution
ser.map(lambda x: len(x))

0    3
1    2
2    3
3    6
dtype: int64

**Exercice 19**

In [ ]:
# Input
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

# Solution
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

**Exercice 20**

In [ ]:
# Input
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution 1
from dateutil.parser import parse
ser.map(lambda x: parse(x))

# Solution 2
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

**Exercice 21**

In [ ]:
# Input
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))

# day of month
print("Date: ", ser_ts.dt.day.tolist())

# week number
print("Week number: ", ser_ts.dt.weekofyear.tolist())

# day of year
print("Day number of year: ", ser_ts.dt.dayofyear.tolist())

# day of week
print("Day of week: ", ser_ts.dt.weekday.tolist())

Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day number of year:  [1, 33, 63, 94, 125, 157]
Day of week:  [4, 2, 5, 3, 0, 5]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  if sys.path[0] == '':

**Exercice 22**

In [ ]:
import pandas as pd
# Input
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

# Solution 1
from dateutil.parser import parse
# Parse the date
ser_ts = ser.map(lambda x: parse(x))

# Construct date string with date as 4
ser_datestr = ser_ts.dt.year.astype('str') + '-' + ser_ts.dt.month.astype('str') + '-' + '04'

# Format it.
[parse(i).strftime('%Y-%m-%d') for i in ser_datestr]

# Solution 2
ser.map(lambda x: parse('04 ' + x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

**Exercice 23**

In [ ]:
# Input
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

# Solution
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

**Exercice 24**

In [ ]:
# Input
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])

# Solution 1 (as series of strings)
import re
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
mask = emails.map(lambda x: bool(re.match(pattern, x)))
emails[mask]

# Solution 2 (as series of list)
emails.str.findall(pattern, flags=re.IGNORECASE)

# Solution 3 (as list)
[x[0] for x in [re.findall(pattern, email) for email in emails] if len(x) > 0]

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

**Exercice 25**

In [ ]:
# Input
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

# Solution
weights.groupby(fruit).mean()

apple     5.666667
banana    4.500000
carrot    5.800000
dtype: float64

**Exercice 26**

In [ ]:
# Input
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

# Solution 
sum((p - q)**2)**.5

# Solution (using func)
np.linalg.norm(p-q)

18.16590212458495

**Exercice 27**

In [ ]:
# Input
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

# Solution
dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs

array([1, 5, 7])

**Exercice 28**

In [ ]:
# Input
my_str = 'dbc deb abed gade'

# Solution
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
"".join(ser.replace(' ', least_freq))

d    4
b    3
e    3
     3
a    2
c    1
g    1
dtype: int64

'dbcgdebgabedggade'

**Exercice 29**

In [ ]:
# Solution
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    9
2000-01-08    2
2000-01-15    3
2000-01-22    8
2000-01-29    6
2000-02-05    6
2000-02-12    6
2000-02-19    1
2000-02-26    6
2000-03-04    7
Freq: W-SAT, dtype: int64

**Exercice 30**

In [ ]:
# Input
ser = pd.Series([1,10,3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

# Solution
ser.resample('D').ffill()  # fill with previous value

# Alternatives
ser.resample('D').bfill()  # fill with next value
ser.resample('D').bfill().ffill()  # fill next else prev value

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

**Exercice 31**

In [ ]:
# Input
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

# Solution
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

[0.09, -0.01, 0.4, 0.02, -0.08, 0.37, 0.12, 0.2, 0.2, -0.23]
Lag having highest correlation:  3

**Exercice 32**

In [ ]:
# Solution 1: Use chunks and for-loop
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])


# Solution 2: Use chunks and list comprehension
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
df2 = df2.transpose()


print(df2.head())

        crim    zn  indus  chas    nox  ...    tax  ptratio       b  lstat  medv
0    0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98  24.0
50   0.08873  21.0   5.64   0.0  0.439  ...  243.0     16.8  395.56  13.45  19.7
100  0.14866   0.0   8.56   0.0  0.520  ...  384.0     20.9  394.76   9.42  27.5
150  1.65660   0.0  19.58   0.0  0.871  ...  403.0     14.7  372.80  14.10  21.5
200  0.01778  95.0   1.47   0.0  0.403  ...  402.0     17.0  384.30   4.45  32.9

[5 rows x 14 columns]

**Exercice 33**

In [ ]:
# Solution 1: Using converter parameter
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', 
                 converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})




print(df.head())

      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98   Low
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14   Low
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  High
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  High
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  High

[5 rows x 14 columns]

**Exercice 34**

In [ ]:
L = pd.Series(range(15))

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

**Exercice 35**

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2

**Exercice 36**

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

#  number of rows and columns
print(df.shape)

# datatypes
print(df.dtypes)

# how many columns under each dtype
print(df.dtypes.value_counts())

# summary statistics
df_stats = df.describe()

# numpy array 
df_arr = df.values

# list
df_list = df.values.tolist()

(93, 27)
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object
float64    18
object      9
dtype: int64

**Exercice 37**

In [ ]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
# Get Manufacturer with highest price
df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model', 'Type']]

# Get Row and Column number
row, col = np.where(df.values == np.max(df.Price))

print(row)
print(col)

[58]
[4]

**Exercice 38**

In [ ]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
# Step 1:
df=df.rename(columns = {'Type':'CarType'})
# or
df.columns.values[2] = "CarType"

# Step 2:
df.columns = df.columns.map(lambda x: x.replace('.', '_'))
print(df.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

**Exercice 39**

In [ ]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
df.isnull().values.any()

True

**Exercice 40**

In [ ]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
n_missings_each_col = df.apply(lambda x: x.isnull().sum())
n_missings_each_col.argmax()

23

**Exercice 41**

In [ ]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091

**Exercice 42**

In [ ]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))

**Exercice 43**

In [ ]:
# Input
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution
type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [0]])

# Alternately the following returns a Series
type(df.a)
type(df['a'])
type(df.loc[:, 'a'])
type(df.iloc[:, 1])

pandas.core.series.Series

**Exercice 44**

In [ ]:
# Input
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution Q1
df[list('cbade')]

# Solution Q2 - No hard coding
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

df1 = switch_columns(df, 'a', 'c')

# Solution Q3
df[sorted(df.columns)]
# or
df.sort_index(axis=1, ascending=False, inplace=True)

**Exercice 45**

In [ ]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
# df

# Show all available options
# pd.describe_option()

**Exercice 46**

In [ ]:
# Input
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

# Solution 1: Rounding
df.round(4)

# Solution 2: Use apply to change format
df.apply(lambda x: '%.4f' % x, axis=1)
# or
df.applymap(lambda x: '%.4f' % x)

# Solution 3: Use set_option
pd.set_option('display.float_format', lambda x: '%.4f' % x)

# Solution 4: Assign display.float_format
pd.options.display.float_format = '{:.4f}'.format
print(df)

# Reset/undo float formatting
pd.options.display.float_format = None

   random
0  0.0000
1  0.0000
2  0.0265
3  0.2096

**Exercice 47**

In [ ]:
# Input
df = pd.DataFrame(np.random.random(4), columns=['random'])

# Solution
out = df.style.format({
    'random': '{0:.2%}'.format,
})

out

**Exercice 48**

In [ ]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

**Exercice 49**

In [ ]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

# Solution
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)
print(df)

True
                          Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small              Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize         missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                   Audi       90  Compact       25.9       32.3
Audi_100_Midsize                  Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                   BMW     535i  Midsize        NaN        NaN
...                                ...      ...      ...        ...        ...
Volkswagen_Eurovan_Van      Volkswagen  Eurovan      Van       16.6       22.7
Volkswagen_Passat_Compact   Volkswagen   Passat  Compact       17.6       22.4
Volkswagen_Corrado_Sporty   Volkswagen  Corrado   Sporty       22.9       23.7
Volvo_240_Compact                Volvo      240  Compact       21.8       23.5
missing_850_Midsize            missing      850  Midsize       24.8       28.5

[93 rows x 5 columns]

**Exercice 50**

In [ ]:
# Input
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

# Solution
n = 5
df['a'].argsort()[::-1][n]

1

**Exercice 51**

In [ ]:
# Input
ser = pd.Series(np.random.randint(1, 100, 15))

# Solution
print('ser: ', ser.tolist(), 'mean: ', round(ser.mean()))

ser:  [80, 4, 31, 86, 63, 93, 12, 57, 75, 17, 43, 1, 36, 11, 86] mean:  46

**Exercice 52**

In [ ]:
# Input
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Solution
# print row sums
rowsums = df.apply(np.sum, axis=1)

# last two rows with row sum greater than 100
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]

**Exercice 53**

In [ ]:
# Input
ser = pd.Series(np.logspace(-2, 2, 30))

# Solution
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high)
    ser[ser < low] = low
    ser[ser > high] = high
    return(ser)

capped_ser = cap_outliers(ser, .05, .95)

0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.876672220183934

**Exercice 54**

In [ ]:
# Input
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
print(df)

# Solution
# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

# Step 2: find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))

# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

    0   1   2   3   4   5   6   7   8   9
0  28  42  16   5  19  29  29  -8   4 -15
1  49  16  20  13  33  28  -8 -14 -14  15
2  11  18   8  48  49  27 -10 -20  -5  -1
3  -3  30  39  12   4  -1 -12  -2 -20  31
4  -5  13  29  26  35   5  -5  17  -5 -20
5  37  47  18  15   5  11  10   1  -8  48
6   2 -16 -10  33 -13   4   2  30 -20   1
7  26  49 -11  -6  48  30  19  40  36  23
8   0  -5  -2  31 -19  31  33   5 -18  32
9  14  32  41   7  30 -20   9  -3  -8  33
[[28. 42. 16.  5. 19. 29. 29.  4.]
 [49. 16. 20. 13. 33. 28. 15. 11.]
 [18.  8. 48. 49. 27. 30. 39. 12.]
 [ 4. 31. 13. 29. 26. 35.  5. 17.]
 [37. 47. 18. 15.  5. 11. 10. 48.]
 [ 2. 33.  4. 30. 26. 49. 48. 30.]
 [19. 40. 36. 23. 31. 31. 33.  5.]
 [32. 14. 32. 41.  7. 30.  9. 33.]]

**Exercice 55**

In [ ]:
# Input
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Solution
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

print(swap_rows(df, 1, 2))

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24

**Exercice 56**

In [ ]:
# Input
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Solution 1
df.iloc[::-1, :]

# Solution 2
print(df.loc[df.index[::-1], :])

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

**Exercice 57**

In [ ]:
# Input
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

# Solution
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)
print(df_onehot)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

**Exercice 58**

In [ ]:

df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

# Solution
print('Column with highest row maxes: ', df.apply(np.argmax, axis=1).value_counts().index[0])

Column with highest row maxes:  3

**Exercice 59**

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

# Solution
import numpy as np

# init outputs
nearest_rows = []
nearest_distance = []

# iterate rows.
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {}  # init dict to store euclidean dists for current row.
    # iterate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist and update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance value
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance

**Exercice 60**

In [ ]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
df

# Solution
abs_corrmat = np.abs(df.corr())
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])
print('Maximum Correlation possible for each column: ', np.round(max_corr.tolist(), 2))

Maximum Correlation possible for each column:  [0.8  0.66 0.66 0.71 0.66 0.83 0.44 0.83 0.8  0.66]

**Exercice 61**

In [ ]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution 1
min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)

# Solution 2
min_by_max = np.min(df, axis=1)/np.max(df, axis=1)

**Exercice 62**

In [ ]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution
out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate'] = out
print(df)

    0   1   2   3   4  ...   6   7   8   9  penultimate
0  76  19  18  53  54  ...  15  14   7  34           76
1  18  98  36  71  74  ...   1  67  85  73           85
2  39  33  49  77  91  ...  24  48  78  61           78
3  20  84  16  25  85  ...   7  24   7  44           84
4  56  65  88  65  15  ...  75   5   4  83           83
5  95  23  85  42  34  ...  66  68  52  53           85
6  69  76   2  45  28  ...  26  71  28  31           76
7  41   8  29  19  47  ...  85  62  49   5           77

[8 rows x 11 columns]

**Exercice 63**

In [ ]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution Q1
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
print('Solution Q1\n',out1)

# Solution Q2
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print('Solution Q2\n', out2)

Solution Q1
       0     1     2     3     4     5     6     7     8     9
0  1.13 -1.09 -1.21 -2.03 -0.79 -1.98 -0.12 -1.99 -0.36 -0.37
1  0.42  0.46  0.38 -0.37  1.96  0.49  1.41 -0.62  1.28  0.10
2 -0.45  0.54  1.34 -0.59  0.30 -0.02  1.15  0.01 -0.88  1.57
3 -0.83 -1.14 -0.66  1.22 -0.41 -0.13 -1.31  1.26  1.19  0.78
4 -0.45 -1.29 -1.13  0.57 -0.23  0.24  0.03  0.52 -1.23  0.26
5 -1.48  0.90 -0.17  0.64 -1.01 -0.69 -0.45 -0.16  0.70 -1.06
6  0.15  1.14  1.37  0.35 -0.69  1.23 -1.23  0.86  0.28 -1.58
7  1.51  0.49  0.08  0.21  0.86  0.86  0.52  0.12 -0.98  0.31
Solution Q2
       0     1     2     3     4     5     6     7     8     9
0  0.13  0.91  1.00  1.00  0.93  1.00  0.56  1.00  0.65  0.62
1  0.36  0.28  0.38  0.49  0.00  0.23  0.00  0.58  0.00  0.47
2  0.65  0.24  0.01  0.56  0.56  0.39  0.10  0.39  0.86  0.00
3  0.78  0.94  0.79  0.00  0.80  0.43  1.00  0.00  0.04  0.25
4  0.65  1.00  0.97  0.20  0.74  0.31  0.51  0.23  1.00  0.42
5  1.00  0.10  0.60  0.18  1.00  0.60  0.68  0.44  0.23  0.83
6  0.45  0.00  0.00  0.27  0.89  0.00  0.97  0.12  0.40  1.00
7  0.00  0.27  0.50  0.31  0.37  0.11  0.33  0.35  0.90  0.40

**Exercice 64**

In [ ]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution
[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

[0.2, 0.78, 0.52, 0.34, 0.34, 0.16, -0.04]

**Exercice 65**

In [ ]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

# Solution
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0

**Exercice 66**

In [ ]:
# Input
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])

# Solution 1
df_grouped.get_group('apple')

# Solution 2
for i, dff in df_grouped:
    if i == 'apple':
        print(dff)

    col1      col2  col3
0  apple  0.598331     7
3  apple  0.014380     6
6  apple  0.880438     7

**Exercice 67**

In [ ]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

print(df)

# Solution
df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-2]

    fruit     taste  price
0   apple  0.526836      1
1  banana  0.048653     14
2  orange  0.103425      7
3   apple  0.820028     13
4  banana  0.167430      2
5  orange  0.400487      3
6   apple  0.624266      3
7  banana  0.876987      9
8  orange  0.931283      5

0.16742975814123218

**Exercice 68**

In [ ]:
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

# Solution
out = df.groupby('fruit', as_index=False)['price'].mean()
print(out)

    fruit  price
0   apple      2
1  banana      5
2  orange      9

**Exercice 69**

In [ ]:
# Input
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

# Solution
pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], suffixes=['_left', '_right'])

    fruit weight  price_left  pazham  kilo  price_right
0   apple   high           7   apple  high           13
1   apple   high           8   apple  high           13
2   apple   high           7   apple  high           13
3  orange    low           9  orange   low            9
4  orange    low           6  orange   low            9
5  orange    low           9  orange   low            9

**Exercice 70**

In [ ]:
# Input
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

# Solution
np.where(df.fruit1 == df.fruit2)

(array([8]),)

**Exercice 71** 
partir de df1, supprimez les lignes présentes dans df2. Les trois colonnes doivent être identiques

In [ ]:
df1 = pd.DataFrame({'fruit': ['apple', 'orange', 'banana'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.arange(9)})

df2 = pd.DataFrame({'fruit': ['apple', 'orange', 'pine'] * 2,
                    'weight': ['high', 'medium'] * 3,
                    'price': np.arange(6)})


# Solution
print(df1[~df1.isin(df2).all(1)])

    fruit  weight  price
2  banana     low      2
3   apple    high      3
4  orange  medium      4
5  banana     low      5
6   apple    high      6
7  orange  medium      7
8  banana     low      8

**Exercice 71**

Comment créer des décalages et des avances d'une colonne dans une dataframe ?
Créez deux nouvelles colonnes dans df, dont l'une est un lag1 (déplacer la colonne vers le abas d'une ligne) de la colonne 'a' et l'autre est une lead1 (déplacer la colonne vers b le haut d'une ligne). Saisir

In [ ]:
# Input
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

# Solution
df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)
print(df)

    a   b   c   d  a_lag1  b_lead1
0   6  73  49  67     NaN     24.0
1  61  24  45  30     6.0     80.0
2  33  80  70  29    61.0     60.0
3  84  60  63  62    33.0     37.0
4  85  37  37  35    84.0      NaN


**Exercice 72**
Obtenez la fréquence des valeurs uniques dans l'ensemble de la trame de données df. Saisir

In [ ]:
# Input
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

# Solution
pd.value_counts(df.values.ravel())

8    4
7    4
6    3
9    2
5    2
2    2
1    2
3    1
dtype: int64

**Exercice 73**

In [ ]:
# Input
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

# Solution
df_out = df.row.str.split(',|\t', expand=True)

# Make first row as header
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka